spring:
  profiles:
    active:
	- dev
---
#开发环境
spring:
  profiles: dev    
  application:
    name: microservicecloud-config-ccg-dev
---
#测试环境
spring:
  profiles: test     
  application:
    name: microservicecloud-config-ccg-test
# 请保存为UTF-8格式